### ISSUE TITLE
can i use this library for optimizing audios too ? 

### ISSUE THREAD

**Issue by hvar90** [WindSekirun/MediaResizer#5]
can i use this library for optimizing audios too ? 
how could i do that ? 
or do you know a library for doing that ? 

thanks for your answer

**Comment by WindSekirun** [comment]
'optimizing audios' means encoding audio or change audio format such as mp3 to wav?
if so, this library can't cover that feature.

**Comment by hvar90** [comment]
> 'optimizing audios' means encoding audio or change audio format such as mp3 to wav?
> if so, this library can't cover that feature.

i mean to reduce sie of audios, is possible do that ?

**Comment by WindSekirun** [comment]
I don't think that feature which you said is possible in Java language, it can be possible with JNI.
Exactly, 'recue size of audio' means 'encoding audio into lower bitrate or lower resolution'. 

you can [encoding audio with FFmpeg](https://stackoverflow.com/a/12952172) and there are some [wrapper of FFmpeg to available in Android environment](https://github.com/topics/ffmpeg-wrapper). 
You should check this article and librarys.
